[PremierContact]
mail_path = "./mails/premier_contact"
objet = "Invitation à la 41ème édition du Forum-Est Horizon"
attachements = [
	"plaquettes/Aide_inscription.pdf",
	"plaquettes/Presentation_Forum_Est_Horizon.pdf",
	"plaquettes/Descriptif_de_l_offre.pdf",
]

[Relance]
mail_path = "./mails/relance"
objet = "Relance sur la participation au Forum Est-Horizon"
attachements = [
	"plaquettes/Aide_inscription.pdf",
	"plaquettes/Presentation_Forum_Est_Horizon.pdf",
	"plaquettes/Descriptif_de_l_offre.pdf",
]

[GuideExposant]
mail_path = "./mails/guide_exposant"
objet = "Guide de l’exposant pour le Forum Est-Horizon"
attachements = [
	"plaquettes/Guide_de_l_exposant.pdf",
	"plaquettes/CATALOGUE_COMPLET_PRESTATIONS_COMPLEMENTAIRES.pdf",
]

[PackPartenaire]
mail_path = "./mails/pack_partenaire"
objet = "Forum Est-Horizon : Informations sur votre sélection du pack Partenaire"
attachements = [
	"plaquettes/Guide_de_l_exposant.pdf",
	"plaquettes/CATALOGUE_COMPLET_PRESTATIONS_COMPLEMENTAIRES.pdf",
]

[PackOr]
mail_path = "./mails/pack_or"
objet = "Forum Est-Horizon : Informations sur votre sélection du pack Or"
attachements = [
	"plaquettes/Guide_de_l_exposant.pdf",
	"plaquettes/CATALOGUE_COMPLET_PRESTATIONS_COMPLEMENTAIRES.pdf",
]

[PackArgent]
mail_path = "./mails/pack_argent"
objet = "Forum Est-Horizon : Informations sur votre sélection du pack Argent"
attachements = [
	"plaquettes/Guide_de_l_exposant.pdf",
	"plaquettes/CATALOGUE_COMPLET_PRESTATIONS_COMPLEMENTAIRES.pdf",
]

[PackBronze]
mail_path = "./mails/pack_bronze"
objet = "Forum Est-Horizon : Informations sur votre sélection du pack Bronze"
attachements = [
	"plaquettes/Guide_de_l_exposant.pdf",
	"plaquettes/CATALOGUE_COMPLET_PRESTATIONS_COMPLEMENTAIRES.pdf",
]

